.github: Enable cdefs tests for build-only targets
We can at least validate the include files during CI.

Signed-off-by: Keith Packard <keithp@keithp.com>

diff --git a/.github/do-build b/.github/do-build
--- a/.github/do-build
+++ b/.github/do-build
@@ -10,6 +10,9 @@ done
 
 ANALYZER="-Danalyzer=true"
 
+CDEFS="-Dtests-cdefs=true"
+TEST="test"
+
 # Disable analyzer on m68k because the compiler gets very confused
 # about complex values
 
@@ -32,9 +35,9 @@ mkdir "$DIR"
 trap 'rm -rf "$DIR"' 0 1 15
 (cd "$DIR" || exit 1
  echo '##################################################'
- echo '##########' ../scripts/"$CONFIGURE" -Dwerror=true $ANALYZER "$@"
+ echo '##########' ../scripts/"$CONFIGURE" -Dwerror=true $ANALYZER $CDEFS "$@"
  echo '##################################################'
- ../scripts/"$CONFIGURE" -Dwerror=true $ANALYZER "$@"
+ ../scripts/"$CONFIGURE" -Dwerror=true $ANALYZER $CDEFS "$@"
  case $? in
      0)
 	 echo 'Configuration succeeded'
@@ -50,4 +53,4 @@ trap 'rm -rf "$DIR"' 0 1 15
 	 ;;
  esac
  cat meson-logs/*
- ninja || exit 1) || exit 1
+ ninja $TEST || exit 1) || exit 1
