.github: Reduce log spam
Adjust the build scripts so they only dump full details when a failure
occurs.

Signed-off-by: Keith Packard <keithp@keithp.com>

diff --git a/.github/do-build b/.github/do-build
--- a/.github/do-build
+++ b/.github/do-build
@@ -15,8 +15,7 @@ done
 
 ANALYZER="-Danalyzer=true"
 
-CDEFS="-Dtests-cdefs=true"
-TEST="test"
+CDEFS="-Dtests-cdefs=true -Dtests=false"
 
 # Disable analyzer on m68k because the compiler gets very confused
 # about complex values
@@ -36,12 +35,14 @@ case "$*" in
 	;;
 esac
 
-mkdir "$DIR"
-(cd "$DIR" || exit 1
+OPTIONS="$ANALYZER $CDEFS"
+
+(mkdir "$DIR" || exit 1
+ cd "$DIR" || exit 2
  echo '##################################################'
- echo '##########' ../scripts/"$CONFIGURE" -Dwerror=true $ANALYZER $CDEFS "$@"
+ echo '##########' ../scripts/"$CONFIGURE" -Dwerror=true $OPTIONS "$@"
  echo '##################################################'
- ../scripts/"$CONFIGURE" -Dwerror=true $ANALYZER $CDEFS "$@"
+ ../scripts/"$CONFIGURE" -Dwerror=true $OPTIONS "$@"
  case $? in
      0)
 	 echo 'Configuration succeeded'
@@ -51,19 +52,52 @@ mkdir "$DIR"
 	 exit 0
 	 ;;
      *)
-	 echo 'Configuration failed with' "$?"
-	 cat meson-logs/*
-	 exit 1
+	 exit 3
 	 ;;
  esac
- cat meson-logs/*
- ninja $TEST)
+ ninja || exit 4
+ meson test -t 20 || exit 5)
 case $? in
     0)
 	rm -rf "$DIR"
 	;;
+    1)
+	echo '##################################'
+	echo '############# mkdir' "$DIR" 'failed'
+	echo '##################################'
+	exit 1
+	;;
+    2)
+	echo '##################################'
+	echo '############# cd' "$DIR" 'failed'
+	echo '##################################'
+	exit 1
+	;;
+    3)
+	echo '##################################'
+	echo '############# Configuration failed'
+	echo '##################################'
+	cat "$DIR"/meson-logs/meson-log.txt
+	exit 1
+	;;
+    4)
+	echo '##################################'
+	echo '############# Build failed'
+	echo '##################################'
+	exit 1
+	;;
+    5)
+	echo '##################################'
+	echo '############# Test failed'
+	echo '##################################'
+	cat "$DIR"/meson-logs/testlog.txt
+	exit 1
+	;;
     *)
-	exit $?
+	echo '##################################'
+	echo '############# Unknown failure' "$?"
+	echo '##################################'
+	cat "$DIR"/meson-logs/*
+	exit 1
 	;;
 esac
-
diff --git a/.github/do-test b/.github/do-test
--- a/.github/do-test
+++ b/.github/do-test
@@ -38,12 +38,14 @@ case "$*" in
 	;;
 esac
 
-mkdir "$DIR"
-(cd "$DIR" || exit 1
+OPTIONS="$SANITIZER"
+
+(mkdir "$DIR" || exit 1
+ cd "$DIR" || exit 2
  echo '##################################################'
- echo '##########' ../scripts/"$CONFIGURE" -Dwerror=true $SANITIZER "$@"
+ echo '##########' ../scripts/"$CONFIGURE" -Dwerror=true $OPTIONS "$@"
  echo '##################################################'
- ../scripts/"$CONFIGURE" -Dwerror=true $SANITIZER "$@"
+ ../scripts/"$CONFIGURE" -Dwerror=true $OPTIONS "$@"
  case $? in
      0)
 	 echo 'Configuration succeeded'
@@ -53,19 +55,52 @@ mkdir "$DIR"
 	 exit 0
 	 ;;
      *)
-	 echo 'Configuration failed with' "$?"
-	 cat meson-logs/*
-	 exit 1
+	 exit 3
 	 ;;
  esac
- cat meson-logs/*
- ninja && meson test -t 20 -v)
+ ninja || exit 4
+ meson test -t 20 || exit 5)
 case $? in
     0)
 	rm -rf "$DIR"
 	;;
+    1)
+	echo '##################################'
+	echo '############# mkdir' "$DIR" 'failed'
+	echo '##################################'
+	exit 1
+	;;
+    2)
+	echo '##################################'
+	echo '############# cd' "$DIR" 'failed'
+	echo '##################################'
+	exit 1
+	;;
+    3)
+	echo '##################################'
+	echo '############# Configuration failed'
+	echo '##################################'
+	cat "$DIR"/meson-logs/meson-log.txt
+	exit 1
+	;;
+    4)
+	echo '##################################'
+	echo '############# Build failed'
+	echo '##################################'
+	exit 1
+	;;
+    5)
+	echo '##################################'
+	echo '############# Test failed'
+	echo '##################################'
+	cat "$DIR"/meson-logs/testlog.txt
+	exit 1
+	;;
     *)
-	exit $?
+	echo '##################################'
+	echo '############# Unknown failure' "$?"
+	echo '##################################'
+	cat "$DIR"/meson-logs/*
+	exit 1
 	;;
 esac
-
