.github: Make cmake test runs quieter
Capture output and only display it if there's a problem.

Signed-off-by: Keith Packard <keithp@keithp.com>

diff --git a/.github/do-cmake-test b/.github/do-cmake-test
--- a/.github/do-cmake-test
+++ b/.github/do-cmake-test
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 TARGET=$1
 DIR=build-"$TARGET"
 CONFIGURE=do-"$TARGET"-configure
@@ -19,13 +19,15 @@ case "$TARGET" in
         ;;
 esac
 
+export CTEST_PARALLEL_LEVEL=
+
 mkdir $DIR
 trap 'rm -rf "$DIR"' 0
 (cd $DIR || exit 1
  echo '##################################################'
  echo '##########' ../scripts/"$CONFIGURE" "$@"
  echo '##################################################'
- ../scripts/$CONFIGURE "$@"
+ ../scripts/$CONFIGURE "$@" >& config.log
  case $? in
      0)
 	 echo 'Configuration succeeded'
@@ -36,8 +38,29 @@ trap 'rm -rf "$DIR"' 0
 	 ;;
      *)
 	 echo 'Configuration failed'
+	 cat config.log
 	 exit 1
 	 ;;
  esac
- cat CMakeFiles/CMakeOutput.log
- ninja --quiet && ninja --quiet test) || exit 1
+ ninja >& ninja.log
+ case $? in
+     0)
+	 echo 'Build succeeded'
+	 ;;
+     *)
+	 echo 'Build failed'
+	 cat ninja.log
+	 exit 1
+	 ;;
+ esac
+ ninja --quiet test >& test.log
+ case $? in
+     0)
+	 echo 'Tests passed'
+	 ;;
+     *)
+	 echo 'Tests failed'
+	 cat test.log
+	 exit 1
+	 ;;
+ esac) || exit 1
