ci: Upload a patch to fix formatting (#1252)
Signed-off-by: Kushal Pal <kushpal@qti.qualcomm.com>

diff --git a/.github/do-check-format b/.github/do-check-format
--- a/.github/do-check-format
+++ b/.github/do-check-format
@@ -1,3 +1,9 @@
 #!/bin/sh
 git config --global --add safe.directory /picolibc
-git ls-files | xargs clang-format -n --Werror
+git ls-files | xargs clang-format -i
+git diff > clang-format.patch
+if [ -s clang-format.patch ]; then
+    echo "Formatting errors found. Patch to fix them:"
+    cat clang-format.patch
+    exit 1
+fi
