merge from trunk

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -42,7 +42,7 @@
 
 # these libraries are used by various programs built for the host environment
 #
-host_libs="intl mmalloc libiberty opcodes bfd readline db tcl tk tcl8.1 tk8.1 tclX itcl tix libgui zlib"
+host_libs="intl mmalloc libiberty opcodes bfd readline db tcl tk tclX itcl tix libgui zlib"
 
 libstdcxx_version="target-libstdc++-v3"
 # Don't use libstdc++-v3's flags to configure/build itself.
@@ -51,7 +51,7 @@ libstdcxx_flags='`case $$dir in libstdc++-v3 | libjava) ;; *) test ! -f $$r/$(TA
 # these tools are built for the host environment
 # Note, the powerpc-eabi build depends on sim occurring before gdb in order to
 # know that we are building the simulator.
-host_tools="texinfo byacc flex bison binutils ld gas gcc cgen sid sim gdb make patch prms send-pr gprof gdbtest tgas etc expect dejagnu ash bash bzip2 m4 autoconf automake libtool ispell grep diff rcs cvssrc fileutils shellutils time textutils wdiff find emacs emacs19 uudecode hello tar gzip indent recode release sed utils guile perl apache inet gawk findutils snavigator libtool gettext zip fastjar"
+host_tools="texinfo byacc flex bison binutils ld gas gcc cgen sid sim gdb make patch prms send-pr gprof gdbtest tgas etc expect dejagnu ash bash bzip2 m4 autoconf automake libtool ispell grep diff rcs cvssrc fileutils shellutils time textutils wdiff find uudecode hello tar gzip indent recode release sed utils guile perl apache inet gawk findutils snavigator libtool gettext zip fastjar"
 
 # libgcj represents the runtime libraries only used by gcj.
 libgcj="target-libffi \
@@ -93,7 +93,7 @@ target_tools="target-examples target-groff target-gperf"
 #
 # This must be a single line because of the way it is searched by grep in
 # the code below.
-native_only="autoconf automake libtool cvssrc emacs emacs19 fileutils find gawk gettext grep gzip hello indent ispell m4 rcs recode sed shellutils tar textutils uudecode wdiff gprof target-groff guile perl apache inet time ash bash bzip2 prms snavigator gnuserv target-gperf"
+native_only="autoconf automake libtool cvssrc fileutils find gawk gettext grep gzip hello indent ispell m4 rcs recode sed shellutils tar textutils uudecode wdiff gprof target-groff guile perl apache inet time ash bash bzip2 prms snavigator gnuserv target-gperf"
 
 # directories to be built in a cross environment only
 #
@@ -125,11 +125,11 @@ case "${host}" in
   m68k-hp-hpux*)
     # Avoid "too much defining" errors from HPUX compiler.
     tentative_cc="cc -Wp,-H256000"
-    host_makefile_frag="${host_makefile_frag} config/mh-hp300"
+    host_makefile_frag="config/mh-hp300"
     ;;
   m68k-apollo-sysv*)
     tentative_cc="cc -A ansi -A runtype,any -A systype,any -U__STDC__ -DUSG"
-    host_makefile_frag="${host_makefile_frag} config/mh-apollo68"
+    host_makefile_frag="config/mh-apollo68"
     ;;
   m68k-apollo-bsd*)
     #None of the Apollo compilers can compile gas or binutils.  The preprocessor
@@ -139,34 +139,34 @@ case "${host}" in
     # or whatever), but I'm not sure leaving CC as cc is any better...
     #CC=cc -A ansi -A runtype,any -A systype,any -U__STDC__ -DNO_STDARG
     tentative_cc=gcc
-    host_makefile_frag="${host_makefile_frag} config/mh-a68bsd"
+    host_makefile_frag="config/mh-a68bsd"
     ;;
   m88k-dg-dgux*)
     tentative_cc="gcc -Wall -ansi -D__using_DGUX"
-    host_makefile_frag="${host_makefile_frag} config/mh-dgux"
+    host_makefile_frag="config/mh-dgux"
     ;;
   m88k-harris-cxux*)
     # Under CX/UX, we want to tell the compiler to use ANSI mode.
     tentative_cc="cc -Xa"
-    host_makefile_frag="${host_makefile_frag} config/mh-cxux"
+    host_makefile_frag="config/mh-cxux"
     ;;
   m88k-motorola-sysv*)
-    host_makefile_frag="${host_makefile_frag} config/mh-delta88"
+    host_makefile_frag="config/mh-delta88"
     ;;
   mips*-dec-ultrix*)
     tentative_cc="cc -Wf,-XNg1000"
-    host_makefile_frag="${host_makefile_frag} config/mh-decstation"
+    host_makefile_frag="config/mh-decstation"
     ;;
   mips*-nec-sysv4*)
     # The C compiler on NEC MIPS SVR4 needs bigger tables.
     tentative_cc="cc -ZXNd=5000 -ZXNg=1000"
-    host_makefile_frag="${host_makefile_frag} config/mh-necv4"
+    host_makefile_frag="config/mh-necv4"
     ;;
   mips*-sgi-irix6*)
-    host_makefile_frag="${host_makefile_frag} config/mh-irix6"
+    host_makefile_frag="config/mh-irix6"
     ;;
   mips*-sgi-irix5*)
-    host_makefile_frag="${host_makefile_frag} config/mh-irix5"
+    host_makefile_frag="config/mh-irix5"
     ;;
   mips*-sgi-irix4*)
     # Tell compiler to use K&R C.  We can't compile under the SGI Ansi
@@ -175,10 +175,10 @@ case "${host}" in
     tentative_cc="cc -cckr -Wf,-XNg1500 -Wf,-XNk1000 -Wf,-XNh2000 -Wf,-XNl8192"
     ;;
   mips*-sgi-irix3*)
-    host_makefile_frag="${host_makefile_frag} config/mh-sysv"
+    host_makefile_frag="config/mh-sysv"
     ;;
   mips*-*-sysv4*)
-    host_makefile_frag="${host_makefile_frag} config/mh-sysv4"
+    host_makefile_frag="config/mh-sysv4"
     ;;
   mips*-*-sysv*)
     # This is for a MIPS running RISC/os 4.52C.
@@ -194,24 +194,24 @@ case "${host}" in
     # This is not part of CFLAGS because perhaps not all C compilers have this
     # option.
     tentative_cc="cc -systype sysv"
-    host_makefile_frag="${host_makefile_frag} config/mh-riscos"
+    host_makefile_frag="config/mh-riscos"
     ;;
   i370-ibm-opened*)
     tentative_cc="c89"
-    host_makefile_frag="${host_makefile_frag} config/mh-openedition"
+    host_makefile_frag="config/mh-openedition"
     ;;
   i[3456]86-*-sysv5*)
-    host_makefile_frag="${host_makefile_frag} config/mh-sysv5"
+    host_makefile_frag="config/mh-sysv5"
     ;;
   i[3456]86-*-dgux*)
     tentative_cc="gcc -Wall -ansi -D__using_DGUX"
-    host_makefile_frag="${host_makefile_frag} config/mh-dgux386"
+    host_makefile_frag="config/mh-dgux386"
     ;;
   i[3456]86-ncr-sysv4.3*)
     # The MetaWare compiler will generate a copyright message unless you
     # turn it off by adding the -Hnocopyr flag.
     tentative_cc="cc -Hnocopyr"
-    host_makefile_frag="${host_makefile_frag} config/mh-ncrsvr43"
+    host_makefile_frag="config/mh-ncrsvr43"
     ;;
   i[3456]86-ncr-sysv4*)
     # for an NCR 3000 (i486/SVR4) system.
@@ -220,47 +220,47 @@ case "${host}" in
     # you run it, but it chokes and dies on a whole bunch of GNU source
     # files.  Default to using the AT&T compiler installed in /usr/ccs/ATT/cc.
     tentative_cc="/usr/ccs/ATT/cc"
-    host_makefile_frag="${host_makefile_frag} config/mh-ncr3000"
+    host_makefile_frag="config/mh-ncr3000"
     ;;
   i[3456]86-*-sco3.2v5*)
-    host_makefile_frag="${host_makefile_frag} config/mh-sysv"
+    host_makefile_frag="config/mh-sysv"
     ;;
   i[3456]86-*-sco*)
     # The native C compiler botches some simple uses of const.  Unfortunately,
     # it doesn't defined anything like "__sco__" for us to test for in ansidecl.h.
     tentative_cc="cc -Dconst="
-    host_makefile_frag="${host_makefile_frag} config/mh-sco"
+    host_makefile_frag="config/mh-sco"
     ;;
   i[3456]86-*-udk*)
-    host_makefile_frag="${host_makefile_frag} config/mh-sysv5"
+    host_makefile_frag="config/mh-sysv5"
     ;;
   i[3456]86-*-isc*)
-    host_makefile_frag="${host_makefile_frag} config/mh-sysv"
+    host_makefile_frag="config/mh-sysv"
     ;;
   i[3456]86-*-solaris2*)
-    host_makefile_frag="${host_makefile_frag} config/mh-sysv4"
+    host_makefile_frag="config/mh-sysv4"
     ;;
   i[3456]86-*-aix*)
-    host_makefile_frag="${host_makefile_frag} config/mh-aix386"
+    host_makefile_frag="config/mh-aix386"
     ;;
   i[3456]86-*-msdosdjgpp*)
-    host_makefile_frag="${host_makefile_frag} config/mh-djgpp"
+    host_makefile_frag="config/mh-djgpp"
     ;;
   *-cygwin*)
-    host_makefile_frag="${host_makefile_frag} config/mh-cygwin"
+    host_makefile_frag="config/mh-cygwin"
     ;;
   *-mingw32*)
-    host_makefile_frag="${host_makefile_frag} config/mh-mingw32"
+    host_makefile_frag="config/mh-mingw32"
     ;;
   *-interix*)
-    host_makefile_frag="${host_makefile_frag} config/mh-interix"
+    host_makefile_frag="config/mh-interix"
     ;;
   vax-*-ultrix2*)
     # The old BSD pcc isn't up to compiling parts of gdb so use gcc
     tentative_cc=gcc
     ;;
   *-*-solaris2*)
-    host_makefile_frag="${host_makefile_frag} config/mh-solaris"
+    host_makefile_frag="config/mh-solaris"
     ;;
   m68k-sun-sunos*)
     # Sun's C compiler needs the -J flag to be able to compile cp-parse.c
@@ -269,30 +269,30 @@ case "${host}" in
     ;;
   *-hp-hpux[78]*)
     tentative_cc="cc -Wp,-H256000"
-    host_makefile_frag="${host_makefile_frag} config/mh-hpux8"
+    host_makefile_frag="config/mh-hpux8"
     ;;
   *-hp-hpux*)
     tentative_cc="cc -Wp,-H256000"
-    host_makefile_frag="${host_makefile_frag} config/mh-hpux"
+    host_makefile_frag="config/mh-hpux"
     ;;
   *-*-hiux*)
     tentative_cc="cc -Wp,-H256000"
-    host_makefile_frag="${host_makefile_frag} config/mh-hpux"
+    host_makefile_frag="config/mh-hpux"
     ;;
   rs6000-*-lynxos*)
     # /bin/cc is less than useful for our purposes.  Always use GCC
     tentative_cc="/usr/cygnus/progressive/bin/gcc"
-    host_makefile_frag="${host_makefile_frag} config/mh-lynxrs6k"
+    host_makefile_frag="config/mh-lynxrs6k"
     ;;
   *-*-lynxos*)
     # /bin/cc is less than useful for our purposes.  Always use GCC
     tentative_cc="/bin/gcc"
     ;;
   *-*-sysv4*)
-    host_makefile_frag="${host_makefile_frag} config/mh-sysv4"
+    host_makefile_frag="config/mh-sysv4"
     ;;
   *-*-sysv*)
-    host_makefile_frag="${host_makefile_frag} config/mh-sysv"
+    host_makefile_frag="config/mh-sysv"
     ;;
 esac
 fi
@@ -446,7 +446,7 @@ target_subdir=${target_alias}
 if test ! -d ${target_subdir} ; then
   if mkdir ${target_subdir} ; then true
   else
-    echo "'*** could not make ${PWD=`pwd`}/${target_subdir}" 1>&2
+    echo "'*** could not make ${PWD=`${PWDCMD-pwd}`}/${target_subdir}" 1>&2
     exit 1
   fi
 fi
@@ -457,7 +457,7 @@ if test x"${build_alias}" != x"${host}" ; then
   if test ! -d ${build_subdir} ; then
     if mkdir ${build_subdir} ; then true
     else
-      echo "'*** could not make ${PWD=`pwd`}/${build_subdir}" 1>&2
+      echo "'*** could not make ${PWD=`${PWDCMD-pwd}`}/${build_subdir}" 1>&2
       exit 1
     fi
   fi
@@ -654,10 +654,10 @@ case "${target}" in
     noconfigdirs="$noconfigdirs target-newlib target-libgloss ${libgcj}"
     ;;
   alpha*-dec-osf*)
-    # ld works, but does not support shared libraries.  emacs doesn't
-    # work.  newlib is not 64 bit ready.  I'm not sure about fileutils.
+    # ld works, but does not support shared libraries.
+    # newlib is not 64 bit ready.  I'm not sure about fileutils.
     # gas doesn't generate exception information.
-    noconfigdirs="$noconfigdirs gas ld emacs fileutils target-newlib target-libgloss"
+    noconfigdirs="$noconfigdirs gas ld fileutils target-newlib target-libgloss"
     ;;
   alpha*-*-*vms*)
     noconfigdirs="$noconfigdirs gdb ld target-newlib target-libgloss ${libgcj}"
@@ -731,6 +731,9 @@ case "${target}" in
   arm-*-riscix*)
     noconfigdirs="$noconfigdirs ld target-libgloss ${libgcj}"
     ;;
+  avr-*-*)
+    noconfigdirs="$noconfigdirs target-libiberty ${libstdcxx_version} ${libgcj}"
+    ;;
   c4x-*-*)
     noconfigdirs="$noconfigdirs ${libstdcxx_version} target-librx target-libgloss ${libgcj}"
     ;;
@@ -772,13 +775,6 @@ case "${target}" in
     # Do configure ld/binutils/gas for this case.
     ;;
   hppa*-*-*)
-    # HP's C compiler doesn't handle Emacs correctly (but on BSD and Mach
-    # cc is gcc, and on any system a user should be able to link cc to
-    # whatever they want.  FIXME, emacs emacs19).
-    case "${CC}" in
-	"" | cc*) noconfigdirs="$noconfigdirs emacs emacs19" ;;
-        *) ;;
-    esac
     # According to Alexandre Oliva <aoliva@redhat.com>, libjava won't
     # build on HP-UX 10.20.
     noconfigdirs="$noconfigdirs ld shellutils ${libgcj}"
@@ -864,13 +860,7 @@ case "${target}" in
     noconfigdirs="$noconfigdirs target-libgloss"
     ;;
   i[3456]86-*-sysv4*)
-    # The SYSV4 C compiler doesn't handle Emacs correctly
-    case "${CC}" in
-	"" | cc*) noconfigdirs="$noconfigdirs emacs emacs19" ;;
-        *) ;;
-    esac
-    # but that's okay since emacs doesn't work anyway
-    noconfigdirs="$noconfigdirs emacs emacs19 target-libgloss ${libgcj}"
+    noconfigdirs="$noconfigdirs target-libgloss ${libgcj}"
     ;;
   i[3456]86-*-beos*)
      noconfigdirs="$noconfigdirs gdb target-newlib target-libgloss ${libgcj}"
@@ -950,17 +940,15 @@ case "${target}" in
     ;;
   mips*-*-irix5*)
     # The GNU linker does not support shared libraries.
-    # emacs is emacs 18, which does not work on Irix 5 (emacs19 does work)
-    noconfigdirs="$noconfigdirs ld gprof emacs target-libgloss ${libgcj}"
+    noconfigdirs="$noconfigdirs ld gprof target-libgloss ${libgcj}"
     ;;
   mips*-*-irix6*)
     # The GNU assembler does not support IRIX 6.
-    # emacs is emacs 18, which does not work on Irix 5 (emacs19 does work)
     # Linking libjava exceeds command-line length limits on at least
     # IRIX 6.2, but not on IRIX 6.5.
     # Also, boehm-gc won't build on IRIX 6.5, according to Jeffrey Oldham
     # <oldham@codesourcery.com>
-    noconfigdirs="$noconfigdirs gas gprof emacs target-libgloss ${libgcj}"
+    noconfigdirs="$noconfigdirs gas gprof target-libgloss ${libgcj}"
     ;;
   mips*-dec-bsd*)
     noconfigdirs="$noconfigdirs gprof target-libgloss ${libgcj}"
@@ -1319,6 +1307,18 @@ if test -n "${target_makefile_frag}" ; then
   target_makefile_frag=mt-frag
 fi
 
+case "$host" in
+  *msdosdjgpp*)
+    enable_gdbtk=no ;;
+esac
+# Determine whether gdb needs tk/tcl or not.
+case "$enable_gdbtk" in
+  no)
+    GDB_TK="" ;;
+  *)
+    GDB_TK="all-tcl all-tk all-itcl all-tix all-libgui" ;;
+esac
+
 # post-target:
 
 # Make sure that the compiler is able to generate an executable.  If it
@@ -1389,12 +1389,12 @@ if test "${shared}" = "yes" ; then
   esac
 fi
 
-# Record target_configdirs and the configure arguments for target and
-# build configuration in Makefile.
-target_configdirs=`echo "${target_configdirs}" | sed -e 's/target-//g'`
-targargs=`echo "${arguments}" | \
+# Base args.  Strip norecursion, cache-file, srcdir, host, build, target.
+# These are the ones we might not want to pass down to subconfigures.
+baseargs=`echo "${arguments}" | \
 	sed -e 's/--no[^ 	]*//' \
 	    -e 's/--cache[a-z-]*=[^ 	]*//' \
+	    -e 's/--sr[a-z-]*=[^ 	]*//' \
 	    -e 's/--ho[a-z-]*=[^ 	]*//' \
 	    -e 's/--bu[a-z-]*=[^ 	]*//' \
 	    -e 's/--ta[a-z-]*=[^ 	]*//'`
@@ -1402,7 +1402,12 @@ targargs=`echo "${arguments}" | \
 # For the build-side libraries, we just need to pretend we're native,
 # and not use the same cache file.  Multilibs are neither needed nor
 # desired.
-buildargs="--cache-file=../config.cache --build=${build_alias} --host=${build_alias} ${targargs}"
+buildargs="--cache-file=../config.cache --build=${build_alias} --host=${build_alias} ${baseargs}"
+
+# Record target_configdirs and the configure arguments for target and
+# build configuration in Makefile.
+target_configdirs=`echo "${target_configdirs}" | sed -e 's/target-//g'`
+targargs=${baseargs}
 
 # Passing a --with-cross-host argument lets the target libraries know
 # whether they are being built with a cross-compiler or being built
