Handle command line arguments for Hexagon
Use --stdin and --args flags in run-* scripts to differ
between CLI args in standard input stream.

Signed-off-by: Kushal Pal <kushpal@qti.qualcomm.com>

diff --git a/scripts/run-aarch64 b/scripts/run-aarch64
--- a/scripts/run-aarch64
+++ b/scripts/run-aarch64
@@ -42,6 +42,31 @@ qemu="qemu-system-aarch64"
 elf="$1"
 shift
 
+while [ $# -gt 0 ]; do
+  case "$1" in
+    --stdin)
+      if [ $# -lt 2 ]; then
+        echo "Error: --stdin requires a quoted string"
+        exit 1
+      fi
+      stdin="$2"
+      shift 2
+      ;;
+    --args)
+      if [ $# -lt 2 ]; then
+        echo "Error: --args requires a quoted string"
+        exit 1
+      fi
+      args="$2"
+      shift 2
+      ;;
+    *)
+      echo "Unknown option: $1"
+      exit 1
+      ;;
+  esac
+done
+
 # Map stdio to a multiplexed character device so we can use it
 # for the monitor and semihosting output
 
@@ -49,35 +74,7 @@ chardev=stdio,mux=on,id=stdio0
 
 # Point the semihosting driver at our new chardev
 
-cmdline="program-name"
-input=""
-done=0
-
-while [ "$done" != "1" ]; do
-    case "$1" in
-        --)
-            shift
-            done=1
-            ;;
-        -s|"")
-            done=1
-            ;;
-        *)
-            cmdline="$cmdline $1"
-            case "$input" in
-                "")
-                    input="$1"
-                    ;;
-                *)
-                    input="$input $1"
-                    ;;
-            esac
-            shift
-            ;;
-    esac
-done
-
-semi=enable=on,chardev=stdio0,arg="$cmdline"
+semi=enable=on,chardev=stdio0,arg="program-name $args"
 
 if nm "$elf" | grep -q aarch64_putc; then
     "$dir"/monitor-e9 $qemu \
@@ -88,9 +85,9 @@ if nm "$elf" | grep -q aarch64_putc; then
         -cpu max \
         -nic none \
         -nographic \
-        -kernel "$elf" "$@"
+        -kernel "$elf"
 else
-    echo "$input" | $qemu -chardev $chardev \
+    echo "$stdin" | $qemu -chardev $chardev \
                           -semihosting-config "$semi" \
                           -monitor none \
                           -serial none \
@@ -98,5 +95,5 @@ else
                           -cpu cortex-a57 \
                           -nic none \
                           -nographic \
-                          -kernel "$elf" "$@"
+                          -kernel "$elf"
 fi
diff --git a/scripts/run-aarch64-fvp b/scripts/run-aarch64-fvp
--- a/scripts/run-aarch64-fvp
+++ b/scripts/run-aarch64-fvp
@@ -41,33 +41,33 @@ elf="$1"
 shift
 
 cmdline_param="cluster0.cpu0.semihosting-cmd_line"
-input="program-name"
-done=0
 
-while [ "$done" != "1" ]; do
-    case "$1" in
-        --)
-            shift
-            done=1
-            ;;
-        -s|"")
-            done=1
-            ;;
-        *)
-            case "$input" in
-                "")
-                    input="$1"
-                    ;;
-                *)
-                    input="$input $1"
-                    ;;
-            esac
-            shift
-            ;;
-    esac
+while [ $# -gt 0 ]; do
+  case "$1" in
+    --stdin)
+      if [ $# -lt 2 ]; then
+        echo "Error: --stdin requires a quoted string"
+        exit 1
+      fi
+      stdin="$2"
+      shift 2
+      ;;
+    --args)
+      if [ $# -lt 2 ]; then
+        echo "Error: --args requires a quoted string"
+        exit 1
+      fi
+      args="$2"
+      shift 2
+      ;;
+    *)
+      echo "Unknown option: $1"
+      exit 1
+      ;;
+  esac
 done
 
-$fvp_exe --quiet --application "$elf" --parameter "$cmdline_param=$input" \
+$fvp_exe --quiet --application "$elf" --parameter "$cmdline_param=program-name $args" \
     --parameter "bp.vis.disable_visualisation=1" \
     --parameter "bp.terminal_0.quiet=1" \
     --parameter "bp.terminal_1.quiet=1" \
diff --git a/scripts/run-arc b/scripts/run-arc
--- a/scripts/run-arc
+++ b/scripts/run-arc
@@ -38,6 +38,31 @@
 elf="$1"
 shift
 
+while [ $# -gt 0 ]; do
+  case "$1" in
+    --stdin)
+      if [ $# -lt 2 ]; then
+        echo "Error: --stdin requires a quoted string"
+        exit 1
+      fi
+      stdin="$2"
+      shift 2
+      ;;
+    --args)
+      if [ $# -lt 2 ]; then
+        echo "Error: --args requires a quoted string"
+        exit 1
+      fi
+      args="$2"
+      shift 2
+      ;;
+    *)
+      echo "Unknown option: $1"
+      exit 1
+      ;;
+  esac
+done
+
 archstring=""
 readelf="arc-zephyr-elf-readelf"
 # If readelf is installed, we can use the attributes
@@ -101,37 +126,9 @@ esac
 
 chardev=stdio,mux=on,id=stdio0
 
-cmdline="program-name"
-input=""
-done=0
-
-while [ "$done" != "1" ]; do
-    case "$1" in
-        --)
-            shift
-            done=1
-            ;;
-        -s|"")
-            done=1
-            ;;
-        *)
-            cmdline="$cmdline $1"
-            case "$input" in
-                "")
-                    input="$1"
-                    ;;
-                *)
-                    input="$input $1"
-                    ;;
-            esac
-            shift
-            ;;
-    esac
-done
-
 # Point the semihosting driver at our new chardev
 
-semi=enable=on,chardev=stdio0,arg="$cmdline"
+semi=enable=on,chardev=stdio0,arg="program-name $args"
 
 # Disable monitor
 
@@ -143,5 +140,5 @@ mon=none
 
 serial=chardev:stdio0
 
-echo "$input" | $qemu -chardev $chardev -semihosting-config "$semi" -monitor "$mon" -serial "$serial" -cpu $cpu -machine arc-sim -nographic -kernel "$elf" -nic none "$@"
+echo "$stdin" | $qemu -chardev $chardev -semihosting-config "$semi" -monitor "$mon" -serial "$serial" -cpu $cpu -machine arc-sim -nographic -kernel "$elf" -nic none "$@"
 #gdb -fullname -args $qemu -chardev $chardev -semihosting-config "$semi" -monitor "$mon" -serial "$serial" -cpu $cpu -nographic -kernel "$elf" -nic none -machine arc-sim "$@"
diff --git a/scripts/run-arm b/scripts/run-arm
--- a/scripts/run-arm
+++ b/scripts/run-arm
@@ -40,6 +40,31 @@ qemu="qemu-system-arm"
 elf="$1"
 shift
 
+while [ $# -gt 0 ]; do
+  case "$1" in
+    --stdin)
+      if [ $# -lt 2 ]; then
+        echo "Error: --stdin requires a quoted string"
+        exit 1
+      fi
+      stdin="$2"
+      shift 2
+      ;;
+    --args)
+      if [ $# -lt 2 ]; then
+        echo "Error: --args requires a quoted string"
+        exit 1
+      fi
+      args="$2"
+      shift 2
+      ;;
+    *)
+      echo "Unknown option: $1"
+      exit 1
+      ;;
+  esac
+done
+
 cpu=unknown
 machine=unknown
 memory=
@@ -246,41 +271,7 @@ chardev=stdio,mux=on,id=stdio0
 
 # Point the semihosting driver at our new chardev
 
-cmdline="program-name"
-input=""
-input_file=""
-done=0
-
-while [ "$done" != "1" ]; do
-    case "$1" in
-        --)
-            shift
-            done=1
-            ;;
-        -s|"")
-            done=1
-            ;;
-        -i)
-            input_file="$2"
-            shift
-            shift
-            ;;
-        *)
-            cmdline="$cmdline $1"
-            case "$input" in
-                "")
-                    input="$1"
-                    ;;
-                *)
-                    input="$input $1"
-                    ;;
-            esac
-            shift
-            ;;
-    esac
-done
-
-semi=enable=on,chardev=stdio0,arg="$cmdline"
+semi=enable=on,chardev=stdio0,arg="program-name $args"
 
 # Disable monitor
 
@@ -292,15 +283,9 @@ serial=none
 
 export QEMU_AUDIO_DRV=none
 
-case "$input_file" in
-    "")
-        input_file=`mktemp`
-        trap 'rm "$input_file"' 0
-        echo "$input" > "$input_file"
-        ;;
-esac        
 
-"$qemu" $memory \
+echo $stdin | \
+  "$qemu" $memory \
       -chardev "$chardev" \
       -semihosting-config "$semi" \
       -monitor "$mon" \
@@ -309,7 +294,7 @@ esac
       -cpu "$cpu" \
       -device loader,file="$elf",cpu-num=0 \
       -nographic \
-      "$@" < $input_file 
+      "$@"
 
 result=$?
 
diff --git a/scripts/run-hexagon b/scripts/run-hexagon
--- a/scripts/run-hexagon
+++ b/scripts/run-hexagon
@@ -39,35 +39,29 @@ simulator="qemu-system-hexagon"
 elf="$1"
 shift
 
-cmdline="program-name"
-input=""
-done=0
-
-while [ "$done" != "1" ]; do
-    case "$1" in
-        --)
-            shift
-            done=1
-            ;;
-        -s|"")
-            done=1
-            ;;
-        *)
-            cmdline="$cmdline $1"
-            case "$input" in
-                "")
-                    input="$1"
-                    ;;
-                *)
-                    input="$input $1"
-                    ;;
-            esac
-            shift
-            ;;
-    esac
+while [ $# -gt 0 ]; do
+  case "$1" in
+    --stdin)
+      if [ $# -lt 2 ]; then
+        echo "Error: --stdin requires a quoted string"
+        exit 1
+      fi
+      stdin="$2"
+      shift 2
+      ;;
+    --args)
+      if [ $# -lt 2 ]; then
+        echo "Error: --args requires a quoted string"
+        exit 1
+      fi
+      args="$2"
+      shift 2
+      ;;
+    *)
+      echo "Unknown option: $1"
+      exit 1
+      ;;
+  esac
 done
 
-echo $input
-echo $cmdline
-
-echo $input | $simulator  -cpu v68 -M virt -kernel $elf
+echo $stdin | $simulator  -cpu v68 -M virt -kernel $elf -append "$args"
diff --git a/scripts/run-nios2 b/scripts/run-nios2
--- a/scripts/run-nios2
+++ b/scripts/run-nios2
@@ -40,39 +40,36 @@ dir="$(dirname "$0")"
 elf="$1"
 shift
 
+while [ $# -gt 0 ]; do
+  case "$1" in
+    --stdin)
+      if [ $# -lt 2 ]; then
+        echo "Error: --stdin requires a quoted string"
+        exit 1
+      fi
+      stdin="$2"
+      shift 2
+      ;;
+    --args)
+      if [ $# -lt 2 ]; then
+        echo "Error: --args requires a quoted string"
+        exit 1
+      fi
+      args="$2"
+      shift 2
+      ;;
+    *)
+      echo "Unknown option: $1"
+      exit 1
+      ;;
+  esac
+done
+
 qemu="qemu-system-nios2"
 
 # Point the semihosting driver at our new chardev
 
-cmdline="program-name"
-input=""
-done=0
-
-while [ "$done" != "1" ]; do
-    case "$1" in
-        --)
-            shift
-            done=1
-            ;;
-        -s|"")
-            done=1
-            ;;
-        *)
-            cmdline="$cmdline $1"
-            case "$input" in
-                "")
-                    input="$1"
-                    ;;
-                *)
-                    input="$input $1"
-                    ;;
-            esac
-            shift
-            ;;
-    esac
-done
-
-semi=enable=on,chardev=stdio0,arg="$cmdline"
+semi=enable=on,chardev=stdio0,arg="program-name $args"
 
 # Disable monitor
 
@@ -84,7 +81,7 @@ serial=stdio
 
 machine=10m50-ghrd
 
-echo "$input" | $qemu \
+echo "$stdin" | $qemu \
   -chardev stdio,id=stdio0,mux=on \
   -machine $machine \
   -serial none \
@@ -92,4 +89,4 @@ echo "$input" | $qemu \
   -mon chardev=stdio0,mode=readline \
   -net none \
   -nographic \
-  -kernel "$elf" "$@"
+  -kernel "$elf"
diff --git a/scripts/run-riscv b/scripts/run-riscv
--- a/scripts/run-riscv
+++ b/scripts/run-riscv
@@ -40,6 +40,31 @@ qemu="qemu-system-riscv32"
 elf="$1"
 shift
 
+while [ $# -gt 0 ]; do
+  case "$1" in
+    --stdin)
+      if [ $# -lt 2 ]; then
+        echo "Error: --stdin requires a quoted string"
+        exit 1
+      fi
+      stdin="$2"
+      shift 2
+      ;;
+    --args)
+      if [ $# -lt 2 ]; then
+        echo "Error: --args requires a quoted string"
+        exit 1
+      fi
+      args="$2"
+      shift 2
+      ;;
+    *)
+      echo "Unknown option: $1"
+      exit 1
+      ;;
+  esac
+done
+
 archstring=""
 # If readelf is installed, we can use the .riscv.attributes section
 # in the file to determine required extensions that we need in QEMU.
@@ -139,41 +164,7 @@ chardev=stdio,mux=on,id=stdio0
 
 # Point the semihosting driver at our new chardev
 
-cmdline="program-name"
-input=""
-input_file=""
-done=0
-
-while [ "$done" != "1" ]; do
-    case "$1" in
-        --)
-            shift
-            done=1
-            ;;
-        -s|"")
-            done=1
-            ;;
-        -i)
-            input_file="$2"
-            shift
-            shift
-            ;;
-        *)
-            cmdline="$cmdline $1"
-            case "$input" in
-                "")
-                    input="$1"
-                    ;;
-                *)
-                    input="$input $1"
-                    ;;
-            esac
-            shift
-            ;;
-    esac
-done
-
-semi=enable=on,chardev=stdio0,arg="$cmdline"
+semi=enable=on,chardev=stdio0,arg="program-name $args"
 
 # Disable monitor
 
@@ -183,15 +174,8 @@ mon=none
 
 serial=none
 
-case "$input_file" in
-    "")
-        input_file=`mktemp`
-        trap 'rm "$input_file"' 0
-        echo "$input" > "$input_file"
-        ;;
-esac        
-
-"$qemu" \
+echo $stdin | \
+  "$qemu" \
     -chardev $chardev \
     -semihosting-config "$semi" \
     -monitor "$mon" \
@@ -201,4 +185,4 @@ esac
     -kernel "$elf" \
     -nographic \
     -bios none \
-    -m 2G "$@" < "$input_file"
+    -m 2G
