2006-12-18  Kazu Hirata  <kazu@codesourcery.com>
        Merge from newlib-csl-20060320-branch:
        2006-12-15  Daniel Jacobowitz  <dan@codesourcery.com>

        * m68k/fido-crt0.S (_vector_table): Reference
        _PrivilegeViolationHandler.

        2006-12-15  Daniel Jacobowitz  <dan@codesourcery.com>

        * m68k/fido-crt0.S (_start): Set %vbr for context 0 in
        RAM configs.
        * m68k/fido.sc: Clean up formatting.  Add comments.  Move
        stack and heap end to SDRAM for SRAM and SDRAM configurations.
        Put RedBoot application text in SRAM.

        2006-12-13  Nathan Sidwell  <nathan@codesourcery.com>

        * m68k/Makefile (install_cf): Don't loop over files here.  Only
        install sources for the default multilib.
        (install_fido): Likewise.
        (install_io): Install bsps in one go.

        2006-12-01  Nathan Sidwell  <nathan@codesourcery.com>
                    Kazu Hirata  <kazu@codesourcery.com>

        * configure.in: Recognize fido-*-*.
        * configure: Regenerate.
        * m68k/Makefile.in (CF_ISRS): Use addprefix.
        (FIDO_CRT0, FIDO_BSP, FIDO_OBJS, FIDO_HANDLERS,
        FIDO_UNHOSTED_SCRIPTS, FIDO_HOSTED_SCRIPTS, FIDO_SCRIPTS,
        FIDO_SOURCES, all_fido, fido-%-crt0.o, fido-rom.ld,
        fido-rom-hosted.ld, fido-sram.ld, fido-sram-hosted.ld,
        fido-sdram.ld, fido-sdram-hosted.ld, fido-redboot.ld,
        install_fido): New.
        * m68k/asm.h (mbb): New.
        * m68k/configure.in (DO): Check for __mfido__.
        * m68k/configure: Regenerate.
        * m68k/fido-_exit.c, m68k/fido-crt0.S, m68k/fido-handler.c,
        m68k/fido-hosted.S, m68k/fido-sbrk.c, m68k/fido.h,
        m68k/fido.sc, m68k/fido_profiling.h: New.

diff --git a/libgloss/m68k/configure b/libgloss/m68k/configure
--- a/libgloss/m68k/configure
+++ b/libgloss/m68k/configure
@@ -3175,6 +3175,37 @@ sed 's/^/| /' conftest.$ac_ext >&5
 
 fi
 rm -f conftest.err conftest.$ac_ext
+cat >conftest.$ac_ext <<_ACEOF
+#ifndef __mfido__
+		#error we are not fido
+		#endif
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  DO="fido"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+rm -f conftest.err conftest.$ac_ext
 LDFLAGS=$saved_LDFLAGS
 echo "$as_me:$LINENO: result: $DO" >&5
 echo "${ECHO_T}$DO" >&6
